name: Build and Deploy to Production Repository

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: weniv_world

      - name: Install and build
        run: |
          cd weniv_world
          npm install
          npm run webpack

      - name: Checkout production repository
        uses: actions/checkout@v3
        with:
          repository: weniv/weniv_world_production
          token: ${{ secrets.ACCESS_GITHUB_TOKEN }} # Ensure this PAT has rights to push to weniv/weniv_world_production
          path: weniv_world_production

      - name: Backup main to pre_version branch
        run: |
          cd weniv_world_production
          git checkout pre_version || git checkout -b pre_version
          git rm -rf .
          git config user.name "chimaek"
          git config user.email "pipiru100@gmail.com"
          git commit -m "Clear all data in pre_version"
          git merge main --allow-unrelated-histories --strategy-option=theirs 
          git push -u origin pre_version --force

      - name: Clear main branch
        run: |
          cd weniv_world_production
          git checkout main
          git rm -rf .
          git config user.name "chimaek"
          git config user.email "pipiru100@gmail.com"
          git commit -m "Clear main branch"
          git push

      - name: Copy dist contents to production repository
        run: |
          cp -r weniv_world/dist/* weniv_world_production/
          cd weniv_world_production
          git add .
          git config user.name "chimaek"
          git config user.email "pipiru100@gmail.com"
          git commit -m "Update from source repository"
          git push

# Note: The last step to set GitHub Pages source to dist/index.html should be done manually or you can automate with GitHub API.
